# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/images')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('description', models.CharField(max_length=600, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('calary', models.IntegerField(default=10000, verbose_name='\u0417\u0430\u0440\u043f\u043b\u0430\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0412\u0430\u043a\u0430\u043d\u0441\u0438\u044f',
                'verbose_name_plural': '\u0412\u0430\u043a\u0430\u043d\u0441\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.CharField(choices=[('naryn', '\u041d\u0410\u0420\u042b\u041d'), ('kol', '\u0418\u0441\u0441\u044b\u043a-\u041a\u0443\u043b\u044c'), ('osh', '\u041e\u0428'), ('batken', '\u0411\u0430\u0442\u043a\u0435\u043d'), ('talas', '\u0422\u0430\u043b\u0430\u0441'), ('djalalabad', '\u0414\u0436\u0430\u043b\u0430\u043b-\u0410\u0431\u0430\u0434'), ('chuy', '\u0427\u0443\u0439')], default=3, max_length=50, verbose_name='\u041e\u0431\u043b\u0430\u0441\u0442\u044c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='youtube_video',
            field=models.CharField(default=3, max_length=255, verbose_name='\u0412\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0435\u043e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tour', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0442\u0443\u0440'),
        ),
    ]
