# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0422\u0443\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0422\u0443\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='tour',
            name='text_en',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='tour',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
